version: "3"
services:
  nuxt3-blog-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env.docker
    restart: no
    user: nuxt3-blog
    image: terwer/nuxt3-blog:1.3.0